/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author javam2018
 */
public class JFrmSecre extends javax.swing.JInternalFrame {

    /**
     * Creates new form JFrmAdmin
     */
    public JFrmSecre() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLblCodigo = new javax.swing.JLabel();
        jLblTitulo = new javax.swing.JLabel();
        jTxtCodigoS = new javax.swing.JTextField();
        jLblNombre = new javax.swing.JLabel();
        jTxtNombreS = new javax.swing.JTextField();
        jLblApellido = new javax.swing.JLabel();
        jTxtApellidoS = new javax.swing.JTextField();
        jLblDireccion = new javax.swing.JLabel();
        jTxtDireccionS = new javax.swing.JTextField();
        jLblEmail = new javax.swing.JLabel();
        jLblTelCasa = new javax.swing.JLabel();
        jLblTelMovil = new javax.swing.JLabel();
        jTxtTelMovilS = new javax.swing.JTextField();
        jLblFechaNac = new javax.swing.JLabel();
        jTxtFechaNacS = new javax.swing.JTextField();
        jTxtCuiS = new javax.swing.JTextField();
        jLblCui = new javax.swing.JLabel();
        jLblpass = new javax.swing.JLabel();
        jPsfContraS = new javax.swing.JPasswordField();
        jBtnGuardarS = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblSecre = new javax.swing.JTable();
        jTxtCodigoAdmS = new javax.swing.JTextField();
        jLblCodigoAD = new javax.swing.JLabel();
        jBtnActualizarS = new javax.swing.JButton();
        jBtnEliminarS = new javax.swing.JButton();
        jTxtTelCasaS = new javax.swing.JTextField();
        jTxtEmailS = new javax.swing.JTextField();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximizable(true);
        setResizable(true);

        jLblCodigo.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLblCodigo.setText("Código:");

        jLblTitulo.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        jLblTitulo.setText("Secretaria");

        jTxtCodigoS.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jTxtCodigoS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCodigoSActionPerformed(evt);
            }
        });

        jLblNombre.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLblNombre.setText("Nombre:");

        jTxtNombreS.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N

        jLblApellido.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLblApellido.setText("Apellido:");

        jTxtApellidoS.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jTxtApellidoS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtApellidoSActionPerformed(evt);
            }
        });

        jLblDireccion.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLblDireccion.setText("Dirección:");

        jTxtDireccionS.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jTxtDireccionS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtDireccionSActionPerformed(evt);
            }
        });

        jLblEmail.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLblEmail.setText("Email:");

        jLblTelCasa.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLblTelCasa.setText("Tel. Casa:");

        jLblTelMovil.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLblTelMovil.setText("Tel. Movil:");

        jTxtTelMovilS.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N

        jLblFechaNac.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLblFechaNac.setText("Fecha Nac.");

        jTxtFechaNacS.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N

        jTxtCuiS.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N

        jLblCui.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLblCui.setText("Cui:");

        jLblpass.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLblpass.setText("Contraseña:");

        jPsfContraS.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N

        jBtnGuardarS.setText("Guardar");
        jBtnGuardarS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGuardarSActionPerformed(evt);
            }
        });

        jTblSecre.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTblSecre);

        jTxtCodigoAdmS.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jTxtCodigoAdmS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCodigoAdmSActionPerformed(evt);
            }
        });

        jLblCodigoAD.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLblCodigoAD.setText("Código:");

        jBtnActualizarS.setText("Actualizar");

        jBtnEliminarS.setText("Estado");

        jTxtEmailS.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jTxtEmailS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtEmailSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLblCodigo)
                                .addGap(18, 18, 18)
                                .addComponent(jTxtCodigoS, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLblDireccion)
                                        .addComponent(jLblNombre))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLblEmail)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLblTitulo)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTxtNombreS, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLblApellido)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTxtApellidoS))
                                    .addComponent(jTxtDireccionS)
                                    .addComponent(jTxtEmailS, javax.swing.GroupLayout.Alignment.TRAILING)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(21, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLblFechaNac)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTxtFechaNacS, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLblTelCasa)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTxtTelCasaS, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLblpass)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jPsfContraS, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLblCodigoAD)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTxtCodigoAdmS, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLblTelMovil)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLblCui)
                                                .addGap(23, 23, 23)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTxtTelMovilS, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                                            .addComponent(jTxtCuiS)))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 828, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(45, 45, 45))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnGuardarS, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jBtnActualizarS)
                .addGap(36, 36, 36)
                .addComponent(jBtnEliminarS)
                .addGap(258, 258, 258))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLblTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblCodigo)
                    .addComponent(jTxtCodigoS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLblNombre)
                            .addComponent(jTxtNombreS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLblApellido)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jTxtApellidoS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblDireccion)
                    .addComponent(jTxtDireccionS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLblEmail)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTxtEmailS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblTelCasa)
                    .addComponent(jLblTelMovil)
                    .addComponent(jTxtTelMovilS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtTelCasaS, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblFechaNac)
                    .addComponent(jTxtFechaNacS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblCui)
                    .addComponent(jTxtCuiS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPsfContraS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblCodigoAD)
                    .addComponent(jTxtCodigoAdmS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblpass))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnEliminarS)
                    .addComponent(jBtnActualizarS)
                    .addComponent(jBtnGuardarS))
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnGuardarSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGuardarSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnGuardarSActionPerformed

    private void jTxtDireccionSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtDireccionSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtDireccionSActionPerformed

    private void jTxtCodigoAdmSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCodigoAdmSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCodigoAdmSActionPerformed

    private void jTxtCodigoSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCodigoSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCodigoSActionPerformed

    private void jTxtApellidoSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtApellidoSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtApellidoSActionPerformed

    private void jTxtEmailSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtEmailSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtEmailSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmSecre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmSecre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmSecre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmSecre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmSecre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jBtnActualizarS;
    public javax.swing.JButton jBtnEliminarS;
    public javax.swing.JButton jBtnGuardarS;
    private javax.swing.JLabel jLblApellido;
    private javax.swing.JLabel jLblCodigo;
    private javax.swing.JLabel jLblCodigoAD;
    private javax.swing.JLabel jLblCui;
    private javax.swing.JLabel jLblDireccion;
    private javax.swing.JLabel jLblEmail;
    private javax.swing.JLabel jLblFechaNac;
    private javax.swing.JLabel jLblNombre;
    private javax.swing.JLabel jLblTelCasa;
    private javax.swing.JLabel jLblTelMovil;
    private javax.swing.JLabel jLblTitulo;
    private javax.swing.JLabel jLblpass;
    public javax.swing.JPasswordField jPsfContraS;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTblSecre;
    public javax.swing.JTextField jTxtApellidoS;
    public javax.swing.JTextField jTxtCodigoAdmS;
    public javax.swing.JTextField jTxtCodigoS;
    public javax.swing.JTextField jTxtCuiS;
    public javax.swing.JTextField jTxtDireccionS;
    public javax.swing.JTextField jTxtEmailS;
    public javax.swing.JTextField jTxtFechaNacS;
    public javax.swing.JTextField jTxtNombreS;
    public javax.swing.JTextField jTxtTelCasaS;
    public javax.swing.JTextField jTxtTelMovilS;
    // End of variables declaration//GEN-END:variables
}
